// Package types defines data structures and types used throughout the system
package types

import (
	"database/sql/driver"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

// History represents a conversation history entry
// Contains query-answer pairs and associated knowledge references
// Used for tracking conversation context and history
type History struct {
	Query               string     // User query text
	Answer              string     // System response text
	CreateAt            time.Time  // When this history entry was created
	KnowledgeReferences References // Knowledge references used in the answer
}

// MentionedItem represents a mentioned knowledge base or file
type MentionedItem struct {
	ID     string `json:"id"`
	Name   string `json:"name"`
	Type   string `json:"type"`    // "kb" for knowledge base, "file" for file
	KBType string `json:"kb_type"` // "document" or "faq" (only for kb type)
}

// MentionedItems is a slice of MentionedItem for database storage
type MentionedItems []MentionedItem

// Value implements the driver.Valuer interface for database serialization
func (m MentionedItems) Value() (driver.Value, error) {
	if m == nil {
		return json.Marshal([]MentionedItem{})
	}
	return json.Marshal(m)
}

// Scan implements the sql.Scanner interface for database deserialization
func (m *MentionedItems) Scan(value interface{}) error {
	if value == nil {
		*m = make(MentionedItems, 0)
		return nil
	}
	b, ok := value.([]byte)
	if !ok {
		*m = make(MentionedItems, 0)
		return nil
	}
	return json.Unmarshal(b, m)
}

// Message represents a conversation message
// Each message belongs to a conversation session and can be from either user or system
// Messages can contain references to knowledge chunks used to generate responses
type Message struct {
	// Unique identifier for the message
	ID string `json:"id"                    gorm:"type:varchar(36);primaryKey"`
	// ID of the session this message belongs to
	SessionID string `json:"session_id"`
	// Request identifier for tracking API requests
	RequestID string `json:"request_id"`
	// Message text content
	Content string `json:"content"`
	// Message role: "user", "assistant", "system"
	Role string `json:"role"`
	// References to knowledge chunks used in the response
	KnowledgeReferences References `json:"knowledge_references"  gorm:"type:json,column:knowledge_references"`
	// Agent execution steps (only for assistant messages generated by agent)
	// This contains the detailed reasoning process and tool calls made by the agent
	// Stored for user history display, but NOT included in LLM context to avoid redundancy
	AgentSteps AgentSteps `json:"agent_steps,omitempty" gorm:"type:jsonb,column:agent_steps"`
	// Mentioned knowledge bases and files (for user messages)
	// Stores the @mentioned items when user sends a message
	MentionedItems MentionedItems `json:"mentioned_items,omitempty" gorm:"type:jsonb,column:mentioned_items"`
	// Whether message generation is complete
	IsCompleted bool `json:"is_completed"`
	// Whether this response is a fallback (no knowledge base match found)
	IsFallback bool `json:"is_fallback,omitempty"`
	// Message creation timestamp
	CreatedAt time.Time `json:"created_at"`
	// Last update timestamp
	UpdatedAt time.Time `json:"updated_at"`
	// Soft delete timestamp
	DeletedAt gorm.DeletedAt `json:"deleted_at"            gorm:"index"`
}

// AgentSteps represents a collection of agent execution steps
// Used for storing agent reasoning process in database
type AgentSteps []AgentStep

// Value implements the driver.Valuer interface for database serialization
func (a AgentSteps) Value() (driver.Value, error) {
	if a == nil {
		return json.Marshal([]AgentStep{})
	}
	return json.Marshal(a)
}

// Scan implements the sql.Scanner interface for database deserialization
func (a *AgentSteps) Scan(value interface{}) error {
	if value == nil {
		*a = make(AgentSteps, 0)
		return nil
	}
	b, ok := value.([]byte)
	if !ok {
		*a = make(AgentSteps, 0)
		return nil
	}
	return json.Unmarshal(b, a)
}

// BeforeCreate is a GORM hook that runs before creating a new message record
// Automatically generates a UUID for new messages and initializes knowledge references
// Parameters:
//   - tx: GORM database transaction
//
// Returns:
//   - error: Any error encountered during the hook execution
func (m *Message) BeforeCreate(tx *gorm.DB) (err error) {
	m.ID = uuid.New().String()
	if m.KnowledgeReferences == nil {
		m.KnowledgeReferences = make(References, 0)
	}
	if m.AgentSteps == nil {
		m.AgentSteps = make(AgentSteps, 0)
	}
	if m.MentionedItems == nil {
		m.MentionedItems = make(MentionedItems, 0)
	}
	return nil
}
